name: flutter_application_1
description: A Flutter app connected to Firebase and OpenStreetMap.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0  # ðŸ”¹ Upgraded http package
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  flutter_map: ^8.1.0   # OpenStreetMap support
  latlong2: ^0.9.1      # Helps with latitude & longitude
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.1.14
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true  

  assets:
    - lib/assets/images/google.png
    - lib/assets/images/apple.png
    